### PR TITLE
Add support for 'Command' #161

### PR DESCRIPTION
**Pull request by abizeauMaxon**
To support by feature request with issue #161

### CODE REVIEW

**Comment by Irame** [comment]
Thank you for the contribution and the work you put in!
Sorry for the late response but I haven't got time recently to maintain this extension properly. I will try to look into you PR this weekend. And thank you again, every contribution is greatly appreciated.

**Comment by Irame** [comment]
Hi, I just skimmed through the changes and noticed, that you chose to implement it on the master branch. It would be awesome if you could rebase this PR onto dev/main (or create a new one if that is easier). There are a lot of refactoring changes there which makes the rebase quite tedious, I think.
I also would very much appreciate someone who could test the changes I made there, because currently I don't use the extension that much.

**Comment by abizeauMaxon** [comment]
I'm currently using the version I build daily right now and it works well. It does what I need.

I currently don't have much time to rebase this. But I will try to do it at somepoint.

**Comment by Irame** [comment]
Rebasing this onto the new project structure is very tedious so I just re-implemented it based on the implementation you provided.

**Comment by abizeauMaxon** [comment]
Thanks a lot! Sorry for the burden! But this tool save my life now!! With 300 projects and having multiple app to debug, super easy to define multiple and test on demand! Thanks a lot! Will look into your build instead of my custom fork version

**Comment by Irame** [comment]
It would be great if you could test [v3.0.3](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.0.3). It works great for me but it seems that some people could have issues with this version (see the last few comments in issue #177).

**Pull request closed without merging**
